version: '3.2'

services:
  springapp:
    image: snaketg/spring-boot-mongo:BUILD_NUMBER
    container_name: springappcontainer
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
    - springappnetwork  
  mongo:
    image: mongo
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    volumes:
      - mongodbvol:/data/db
    networks:
    - springappnetwork    
volumes:
  mongodbvol:
    driver: local
networks:
  springappnetwork:
    driver: bridge
